#!/usr/bin/env bash
# Apply a conservative StepMania 5.1 Player 1 controller map for Batocera.

set -euo pipefail

INSTALL_ROOT="${INSTALL_ROOT:-/userdata/system}"
BUNDLE_ROOT="${BUNDLE_ROOT:-${INSTALL_ROOT}/share/stepmania-flatpak-launcher}"
STEPMANIA_FLATPAK_HOME="${STEPMANIA_FLATPAK_HOME:-/userdata/saves/flatpak/data}"
KEYMAPS_PATH="${KEYMAPS_PATH:-${STEPMANIA_FLATPAK_HOME}/.var/app/com.stepmania.StepMania/.stepmania-5.1/Save/Keymaps.ini}"
BACKUP_DIR="${BACKUP_DIR:-${BUNDLE_ROOT}/backups}"
REPORT_PATH="${REPORT_PATH:-${BUNDLE_ROOT}/stepmania-controller-map.json}"
PROFILE="${PROFILE:-xbox-p1}"
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage: apply-controller-map.sh [--dry-run] [--keymaps PATH] [--report PATH]

Writes a StepMania 5.1 Keymaps.ini default for Player 1:
- D-pad / left-stick axes: dance arrows and menu navigation
- B1-B4: alternate dance arrows for simple gamepad play
- B9: Back / Select
- B10: Start

Environment:
  INSTALL_ROOT
  BUNDLE_ROOT
  STEPMANIA_FLATPAK_HOME
  KEYMAPS_PATH
  BACKUP_DIR
  REPORT_PATH
  PROFILE
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      ;;
    --keymaps)
      KEYMAPS_PATH="${2:?missing --keymaps value}"
      shift
      ;;
    --report)
      REPORT_PATH="${2:?missing --report value}"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

controller_names() {
  local found=0
  for name_file in /sys/class/input/js*/device/name; do
    if [ -f "$name_file" ]; then
      found=1
      sed 's/"/\\"/g' "$name_file"
    fi
  done
  if [ "$found" -eq 0 ]; then
    printf 'none\n'
  fi
}

write_keymaps() {
  cat >"$1" <<'EOF'
# Generated by Batocera Rhythm Launchers stepmania-flatpak-launcher/apply-controller-map.sh.
# This maps the first detected joystick as Joy1 for Player 1.

[dance]
1_Back=Joy1_B9:Key_escape
1_Down=Joy1_Down1:Joy1_B2
1_Left=Joy1_Left1:Joy1_B1
1_MenuDown=Joy1_Down1
1_MenuLeft=Joy1_Left1
1_MenuRight=Joy1_Right1
1_MenuUp=Joy1_Up1
1_Right=Joy1_Right1:Joy1_B3
1_Select=Joy1_B9:Key_backspace
1_Start=Joy1_B10:Key_enter
1_Up=Joy1_Up1:Joy1_B4
1_UpLeft=Joy1_B5
1_UpRight=Joy1_B6
EOF
}

json_array_from_lines() {
  awk 'BEGIN { first=1; printf "[" } {
    gsub(/\\/,"\\\\");
    gsub(/"/,"\\\"");
    if (!first) printf ",";
    printf "\"%s\"", $0;
    first=0;
  } END { printf "]" }'
}

controllers="$(controller_names | json_array_from_lines)"
backup_path=""

if [ "$DRY_RUN" -eq 1 ]; then
  status="dry-run"
  generated_sha256=""
else
  mkdir -p "$(dirname "$KEYMAPS_PATH")" "$BACKUP_DIR" "$(dirname "$REPORT_PATH")"
  if [ -f "$KEYMAPS_PATH" ]; then
    backup_path="${BACKUP_DIR}/Keymaps.ini.$(date -u '+%Y%m%dT%H%M%SZ').bak"
    cp -p "$KEYMAPS_PATH" "$backup_path"
  fi
  tmp_path="${KEYMAPS_PATH}.tmp"
  write_keymaps "$tmp_path"
  mv "$tmp_path" "$KEYMAPS_PATH"
  status="applied"
  generated_sha256="$(sha256sum "$KEYMAPS_PATH" | awk '{print $1}')"
fi

cat >"$REPORT_PATH" <<EOF
{
  "schema": "batocera.stepmania-controller-map.v1",
  "status": "$status",
  "profile": "$PROFILE",
  "keymaps_path": "$KEYMAPS_PATH",
  "backup_path": "$backup_path",
  "generated_sha256": "$generated_sha256",
  "controllers": $controllers
}
EOF

printf '%s\n' "$REPORT_PATH"
